FROM apache/hive:4.1.0

USER root



#COPY mssql-jdbc-*.jar /opt/hive/lib/
RUN curl -fL -o /opt/hive/lib/mssql-jdbc-12.10.2.jre11.jar \
    "https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.10.2.jre11/mssql-jdbc-12.10.2.jre11.jar"

COPY hive-site.xml /opt/hive/conf/
USER hive



# RUN mkdir -p /opt/hive/warehouse && chown -R hive:hive /opt/hive/warehouse

#schematool -dbType mssql -initSchema